apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reservation
  name: reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      labels:
        app: reservation
    spec:
      containers:
        - image: sarmad1995/reservations:2
          name: reservations
          env:
            - name: MONGODB_URI
              value: 'mongodb+srv://sarmad:<password>@cluster0.pczb4.mongodb.net/?retryWrites=true&w=majority'
            - name: PORT
              value: '3004'
            - name: AUTH_HOST
              value: auth-tcp
            - name: AUTH_PORT
              value: '3002'
            - name: PAYMENTS_HOST
              value: payments
            - name: PAYMENTS_PORT
              value: '3001'
          ports:
            - containerPort: 3004
